# Generated by Django 4.2.6 on 2023-10-20 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shoper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField(max_length=100)),
                ('discount_price', models.FloatField(max_length=100)),
                ('basi_description', models.TextField(max_length=100)),
                ('details_description', models.TextField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('stock', models.CharField(choices=[('SI', 'In Stock'), ('SO', 'Out Stock')], max_length=40)),
                ('tag', models.CharField(max_length=100)),
                ('product_1_image', models.ImageField(upload_to='productimg')),
                ('product_2_image', models.ImageField(upload_to='productimg')),
                ('product_3_image', models.ImageField(upload_to='productimg')),
                ('product_4_image', models.ImageField(upload_to='productimg')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shoper.categories')),
                ('sub_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shoper.subcategories')),
            ],
        ),
    ]
