# Generated by Django 4.2.6 on 2023-10-24 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubCategory', '0001_initial'),
        ('Category', '0001_initial'),
        ('Shoper', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategories',
            name='cat_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubCategory.subcategories'),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='SubCategories',
        ),
    ]
