# Generated by Django 4.2.6 on 2023-10-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoper', '0004_remove_product_cat_id_remove_product_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_1_image', models.ImageField(upload_to='productimg')),
                ('banner_2_image', models.ImageField(upload_to='productimg')),
                ('banner_3_image', models.ImageField(upload_to='productimg')),
                ('banner_4_image', models.ImageField(upload_to='productimg')),
            ],
        ),
    ]
