# Generated by Django 4.2.6 on 2023-10-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoper', '0005_banner_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner_images',
            old_name='banner_1_image',
            new_name='slider',
        ),
        migrations.RemoveField(
            model_name='banner_images',
            name='banner_2_image',
        ),
        migrations.RemoveField(
            model_name='banner_images',
            name='banner_3_image',
        ),
        migrations.RemoveField(
            model_name='banner_images',
            name='banner_4_image',
        ),
        migrations.AlterField(
            model_name='banner_images',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
