# Generated by Django 4.2.6 on 2023-10-25 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shoper', '0006_rename_banner_1_image_banner_images_slider_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner_Images',
            new_name='BannerImages',
        ),
    ]
