# Generated by Django 4.2.6 on 2023-10-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shoper', '0007_rename_banner_images_bannerimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BannerImages',
            new_name='Banner_Images',
        ),
    ]
