# Generated by Django 4.2.6 on 2023-10-25 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shoper', '0008_rename_bannerimages_banner_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner_Images',
        ),
    ]
