# Generated by Django 4.2.6 on 2023-10-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoper', '0009_delete_banner_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.CharField(max_length=100),
        ),
    ]
