# Generated by Django 4.2.6 on 2023-10-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoper', '0010_product_tag_alter_product_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(max_length=100),
        ),
    ]
