# Generated by Django 4.2.6 on 2023-10-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slider', models.ImageField(upload_to='productimg')),
            ],
        ),
    ]
