# Generated by Django 4.2.6 on 2023-10-24 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.categories')),
            ],
        ),
    ]
