# Generated by Django 4.2.6 on 2024-01-10 04:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_register",
            name="identy_no",
        ),
    ]
